### ISSUE TITLE
[Item 6] - 유한 상태 머신에 대해서

### ISSUE THREAD

**Issue by been1118** [Effective-Java-Study-2023/Effective_Java#7]
은양님께서 질문해주셔서 정리못한 부분 정리합니다..

[Item 6](https://github.com/Effective-Java-Study-2023/Effective_Java/blob/main/2%EC%9E%A5/Item%206.md)

유한 상태 머신 또는 유한 오토마톤이라고도 하는 상태 머신은 추상 머신을 구축하는 데 사용되는 계산 모델입니다. 이러한 기계는 주어진 시간에 하나의 상태에만 있을 수 있습니다. 각 상태는 다른 상태로 변경되는 시스템의 상태입니다. 이러한 상태 변경을 전환이라고 합니다.

[FSM in JAVA](https://www.youtube.com/watch?v=ZfW7FwuBd90) (영어인데 이해하기 어렵진 않은 듯 하빈다.)

 - 가질 수 있는 상태가 한정됩니다. (미리 정해져 있음)
 - 한 번에 한 가지 상태만 될 수 있습니다.
 - 입력이나 이벤트가 기계에 전달됩니다.
 - 각 상태에는 입력에 따라 다음 상태로 바뀌는 전이가 있습니다.

예를 들어 "apple"이라는 패턴을 입력 문자열이 포함하고 있는지 확인하려면

 - 아직 아무 문자도 보지 못한 상태에서 시작
 - 'a'라는 문자를 보면 'a'를 본 상태로 전이
 - 'p'를 보게 되면 'ap'까지 본 상태로 전이되지만 'p'가 아닌 다른 문자를 보게 되면 아직 아무 문자도 보지 못한 상태로 전이
 - 입력 문자열을 모두 소진할 때까지 반복

![image](https://github.com/Effective-Java-Study-2023/Effective_Java/assets/123082067/18069f18-43f2-41fb-959c-b7da1f25464d)

모든 상태와 전이를 찾아놓고 매칭을 하기 때문에 생성비용이 높지만 생성 이후에는 매칭을 빠르게 할 수 있기 때문에 컴파일러를 만들 때 꼭 사용되는 개념이라고 합니다.

잘못되거나 궁금한 부분 남겨주세요..

**Comment by registaPark** [comment]
동현님 최고최고~!!!
